engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  eslint:
    enabled: true
    config:
      config: .eslintrc
    checks:
      import/no-unresolved:
        enabled: false

ratings:
  paths:
  - "src/**"

exclude_paths:
- "build/"
- "config/"
- "coverage/"
- "docs/"
- "node_modules/"
- "scripts/"
